
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 96
#define YY_END_OF_BUFFER 97
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[269] =
    {   0,
       95,   95,   97,   95,    6,    1,   80,   95,   95,   86,
       79,   95,   11,   12,   84,   83,    8,   82,   16,   85,
       95,   95,   15,    7,   61,   88,   63,   94,   13,   14,
       68,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,    9,   87,   10,   81,
       65,    0,    0,    0,    0,    0,   71,   66,   76,    0,
       69,   56,   72,   57,   73,    0,    0,    0,    4,   70,
       92,    0,    0,    0,   14,   13,   58,   60,   64,   62,
       59,   94,   91,   94,    0,   77,   94,   94,   94,   94,
       94,   94,   26,   94,   94,   94,   94,   94,   28,   94,

       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   78,   67,   89,    0,    0,    0,   17,   93,    0,
        0,    0,    4,   74,   75,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   27,   94,   29,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,    0,    0,   90,    0,    0,
        5,   48,   94,   42,   21,   94,   94,   94,   94,   23,
       36,   94,   94,   94,   44,   44,   30,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       39,   94,   94,    0,    0,   40,   46,   46,   19,   94,

       94,   94,   94,   24,   94,   94,   94,   94,   55,   32,
       94,   94,   94,   94,   94,   94,   37,   94,   94,   25,
        0,    0,   94,   94,   22,   51,   45,   45,   53,   54,
       94,   31,   33,   34,   49,   18,   35,   41,   94,   94,
        0,    0,   94,   20,   47,   47,   94,   94,   94,    0,
        0,    0,   43,   50,   38,   52,    0,    0,    0,    0,
        0,    3,    2,    0,    0,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,    1,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   27,   41,   42,   43,   44,
       45,   46,   27,   47,   48,   49,   50,   51,   52,   53,
       27,   54,   55,   56,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    2,    3,    1,    4,    5,    6,    1,    5,    5,
        1,    1,    5,    5,    5,    5,    5,    7,    2,    8,
        8,    9,    5,   10,   11,    2,   12,   13,    9,    5,
       14,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,    1,   15,    9,    5
    } ;

static const flex_int16_t yy_base[283] =
    {   0,
        0,    0,  394, 1080, 1080, 1080,  364,  369,   54,  338,
       50,    0, 1080, 1080,  335,   47, 1080,   46,   46,   51,
       59,   63,  329, 1080,   63,  319,   43,   62, 1080, 1080,
      314,    0,   64,   68,   72,   74,   90,   91,  100,  106,
      107,  123,  124,   63,  133,  135, 1080,   84, 1080, 1080,
     1080,  319,  134,  170,  289,  261, 1080, 1080, 1080,  290,
     1080, 1080, 1080, 1080, 1080,  272,   53,   94,    0, 1080,
     1080,   81,  161,  165, 1080, 1080,  259, 1080, 1080, 1080,
      244,  152, 1080,    0,  164, 1080,  155,  163,  164,  174,
      172,  178,  179,  182,  192,  195,  201,  211,  215,  213,

      217,  223,  230,  232,  241,  243,  246,  255,  264,  266,
      271, 1080,  173,  246,  215,  193,  276, 1080, 1080,  157,
      214,  314,    0, 1080, 1080,  275,  284,  295,  298,  303,
      314,  317,  322,  325,  333,  334,  342,  343,  366,  352,
      294,  359,  360,  364,  372,  365,  379,  378,  384,  391,
      397,  406,  415,  416,  399,  171,  151, 1080,  382,  453,
     1080,  420,  424,  427,  444,  430,  445,  440,  450,  457,
      458,  462,  463,  475,   77,  156,  476,  481,  489,  494,
      502,  501,  515,  431,  482,  482,  514,  518,  519,  531,
      532,  537,  547,  122,   99,  550,  425,  134,  551,  554,

      555,  569,  568,  573,  583,  586,  589,  576,  590,  593,
      605,  608,  620,  613,  621,  636,  637,  635,  643,  636,
       95,   91,  642,  649,  685,  659,  535,  107,  662,  663,
      675,  678,  679,  682,  692,  695,  698,  699,  711,  712,
      120,   50,  724,  717,  639,   64,  725,  738,  739,  244,
      769,  183,  742,  743,  755,  756,  372,  799,  297,  317,
      808, 1080, 1080,  826,  834,  841,  866, 1080,  922,  226,
      936,  944,  952,  959,  973,  988, 1003, 1018, 1030, 1039,
     1050, 1064
    } ;

static const flex_int16_t yy_def[283] =
    {   0,
      268,    1,  268,  268,  268,  268,  268,  269,  268,  268,
      268,  270,  268,  268,  268,  268,  268,  268,  268,  268,
      271,  271,  268,  268,  268,  268,  268,  272,  268,  268,
      268,  273,  272,  272,  272,   35,   35,   35,   37,   35,
       35,   35,   35,   37,   35,   35,  268,  274,  268,  268,
      268,  269,  269,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  275,  276,  277,  268,
      268,  268,  268,  271,  268,  268,  268,  268,  268,  268,
      268,   35,  268,  273,  274,  268,   35,   35,   35,   35,
       37,   37,   37,   37,   37,   37,   35,   35,   35,   37,

       37,   37,   37,   35,   35,   35,   35,   35,   35,   37,
       37,  268,  274,  269,  268,  268,  268,  268,  268,  276,
      276,  278,  277,  268,  268,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       35,   35,   35,   35,   37,  268,  268,  268,  276,  276,
      268,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,  268,  268,   37,   37,   37,   37,
       37,   37,   37,   35,   35,   37,   37,   37,   37,   37,
       37,   37,   37,  268,  268,   37,  268,  268,   37,   37,

       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   35,   35,   37,   37,   37,
      268,  268,   37,   37,   37,   37,  268,  268,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
      279,  268,   37,   37,  268,  268,   37,   37,   37,  279,
      279,  280,   37,   37,   37,   37,  268,  268,  280,  280,
      281,  268,  268,  282,  268,  281,  282,    0,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268
    } ;

static const flex_int16_t yy_nxt[1139] =
    {   0,
        4,    5,    6,    4,    5,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   28,   28,   39,
       28,   40,   28,   28,   28,   41,   42,   43,   28,   44,
       45,   46,   28,   28,   47,   48,   49,   50,   54,   58,
       54,   62,   64,   66,   68,   67,   67,   80,   81,   69,
       65,   63,   67,   67,   59,   70,   72,  246,   73,   73,
       72,  175,   74,   74,   76,  252,   77,   78,   55,   83,
      176,   83,   84,   56,   84,   83,  121,  121,   84,   83,

       67,   67,   84,   89,   82,   82,  109,  122,  112,   92,
       90,   83,   82,   87,   88,   82,   91,   85,   93,   85,
      228,   82,   82,   85,  250,  242,  250,   85,   82,   82,
      241,   94,   97,   95,   82,   98,   99,   82,   82,  113,
       53,   82,   96,  100,   82,   82,  114,  198,  222,  114,
      101,   82,   82,  102,   82,   82,  114,  104,  103,  121,
      121,   82,  105,  106,   82,  221,   82,   82,   82,  176,
      122,   82,  107,  111,   54,  108,   54,  110,   72,   82,
       73,   73,   72,   82,   74,   74,   82,  259,  268,  114,
       82,   83,  195,   82,   82,   82,   82,  268,  127,   82,

       83,   82,   82,  126,   55,  129,  260,   82,   82,   56,
      194,  128,   82,   82,  131,  130,  121,  121,   82,   82,
       82,   82,   82,   82,   82,   82,  157,  122,  132,  133,
       82,   82,   82,   82,   82,   82,   82,   60,   82,   82,
       60,  134,   82,  135,   82,  136,   82,   82,  250,   82,
      250,  156,   53,   82,  138,   82,   82,  137,   82,   82,
      140,  139,  141,  144,   82,   82,   82,  142,  125,   82,
       82,   82,   82,   82,   82,   82,   82,  148,  143,   82,
      146,   82,   82,  124,   82,  145,   82,   82,  158,  118,
       82,  158,  149,   82,  150,   82,  147,  158,  158,   82,

      117,  259,   82,  151,  116,  153,   82,  154,   82,   82,
      155,  152,   82,   82,   82,  163,  160,  160,   82,  162,
      260,  268,   82,   82,  115,   53,   82,  122,   82,   82,
      164,  158,  161,   82,   82,   82,   82,  178,   86,   82,
      268,   82,   82,   79,  165,  168,   82,   82,   82,  169,
      166,  167,   82,   82,   75,   82,   82,  170,   82,   61,
       82,   82,   57,   82,   82,  173,   82,  171,  172,   82,
      175,   82,   82,   82,   82,   53,  257,   82,   82,  176,
       82,   82,  174,   82,  121,  121,   82,   82,   51,  177,
       82,  258,  258,  268,  268,  122,   82,   82,  179,  268,

       82,   82,   82,   82,   82,   82,   82,  181,  183,  180,
       82,   82,   82,   82,  184,   82,   82,   82,  182,   82,
       82,   82,   82,  186,   82,   82,  185,   82,   82,  197,
       82,   82,   82,  187,   82,   82,   82,   82,  198,  188,
      193,  189,   82,   82,   82,  190,   82,  192,  197,  191,
       82,   82,  268,   82,   82,  121,  121,  198,  268,   82,
       82,   82,   82,   82,  196,   82,  122,   82,   82,   82,
       82,   82,   82,   82,  268,  212,   82,  268,  199,   82,
      268,   82,   82,   82,  200,   82,   82,   82,   82,  201,
      268,  202,   82,   82,  268,  268,   82,   82,   82,   82,

       82,   82,   82,   82,   82,   82,   82,  268,  203,   82,
       82,  204,  268,   82,   82,   82,   82,   82,  205,   82,
       82,  213,   82,   82,   82,  214,   82,   82,   82,  206,
       82,  268,   82,   82,   82,   82,  207,   82,  209,  227,
      208,   82,   82,   82,   82,   82,   82,  215,  228,  210,
      211,  216,  268,   82,   82,   82,   82,   82,   82,   82,
       82,   82,  217,  268,  268,  268,   82,   82,  218,  268,
       82,   82,   82,   82,   82,   82,  268,  227,   82,  268,
       82,  268,  220,   82,   82,  219,  228,  268,   82,   82,
       82,   82,   82,   82,   82,   82,  224,  223,   82,   82,

      268,  268,   82,   82,  225,  268,   82,   82,  268,   82,
       82,  226,   82,  268,   82,  268,   82,   82,  229,  232,
       82,   82,  230,  268,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,  231,   82,  233,
      268,   82,   82,  245,  234,   82,   82,  268,   82,   82,
      236,   82,  246,  235,   82,  268,   82,   82,  268,  268,
       82,   82,   82,   82,   82,   82,  268,   82,   82,  237,
      268,  268,   82,   82,  238,   82,   82,   82,  239,   82,
       82,   82,  240,   82,   82,   82,   82,   82,   82,  245,
       82,  243,   82,  268,   82,   82,  268,  244,  246,  268,

       82,   82,   82,   82,   82,   82,   82,  268,  268,  268,
      247,   82,  268,  268,   82,   82,   82,  268,   82,   82,
       82,   82,   82,   82,  268,   82,   82,   82,   82,  268,
       82,   82,  268,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,  268,   82,  268,  248,   82,  268,  268,
       82,   82,   82,  249,   82,   82,  268,  268,   82,  253,
       82,  268,  268,   82,   82,   82,   82,   82,   82,   82,
      268,  254,  255,  257,  256,  268,   82,   82,  268,   82,
       82,   82,   82,   82,   82,   82,   82,  268,  258,  258,
       82,   82,  268,  268,   82,   82,   82,   82,   82,   82,

      262,  262,  268,  262,  268,  262,  268,   82,   82,  263,
      263,  268,  263,  268,  263,  268,  268,  262,  258,  258,
      268,  268,  268,  268,  268,  264,  263,  263,  263,  268,
      263,  268,  263,  265,  268,  263,  263,  268,  263,  268,
      263,  268,  263,  263,  263,  263,  268,  263,  268,  268,
      268,  265,  263,  268,  262,  268,  268,  268,  264,  263,
      268,  268,  268,  263,  268,  268,  265,  263,  263,  268,
      263,  268,  263,  268,  268,  268,  268,  268,  268,  268,
      268,  263,  268,  268,  263,  268,  268,  268,  268,  263,
      268,  265,  268,  268,  268,  268,  263,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  263,   52,   52,  268,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,  268,  268,  268,
       71,   82,  268,  268,  268,   82,   82,   82,   82,   84,
      268,  268,  268,   84,  268,   84,   85,  268,  268,   85,
       85,   85,  268,   85,  119,  119,  119,  119,  119,  268,
      119,  268,  119,  119,  268,  268,  268,  119,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,

      120,  120,  120,  123,  123,  268,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  251,  268,  251,  268,  268,  268,  268,
      268,  251,  261,  268,  268,  268,  268,  268,  261,  268,
      261,  266,  266,  266,  268,  266,  266,  268,  268,  268,
      268,  266,  268,  268,  266,  267,  267,  267,  268,  267,
      268,  268,  268,  268,  268,  267,  268,  268,  267,    3,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268
    } ;

static const flex_int16_t yy_chk[1139] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   11,
        9,   16,   18,   19,   20,   19,   19,   27,   27,   20,
       18,   16,   67,   67,   11,   20,   21,  246,   21,   21,
       22,  175,   22,   22,   25,  242,   25,   25,    9,   28,
      175,   33,   28,    9,   33,   34,   68,   68,   34,   35,

       72,   72,   35,   35,   44,   36,   44,   68,   48,   36,
       35,   48,   36,   33,   34,   44,   35,   28,   36,   33,
      228,   37,   38,   34,  241,  222,  241,   35,   37,   38,
      221,   37,   38,   37,   37,   38,   39,   40,   41,   48,
       53,   39,   37,   39,   40,   41,   53,  198,  195,   53,
       40,   41,   39,   41,   42,   43,   53,   43,   42,  120,
      120,   42,   43,   43,   45,  194,   46,   42,   43,  176,
      120,   45,   43,   46,   54,   43,   54,   45,   73,   46,
       73,   73,   74,   82,   74,   74,   87,  252,   85,   53,
       82,   85,  157,   87,   88,   89,   82,  113,   88,   87,

      113,   88,   89,   87,   54,   90,  252,   88,   89,   54,
      156,   89,   90,   91,   92,   91,  121,  121,   90,   92,
       93,   92,   93,   94,   91,   94,  116,  121,   93,   94,
       92,   93,   97,   95,   94,   95,   96,  270,   96,   97,
      270,   95,   98,   96,   95,   97,   99,   96,  250,   98,
      250,  115,  114,   99,  100,   98,  100,   98,  101,   99,
      101,  100,  102,  104,  102,  100,  102,  103,   81,  101,
      104,  103,  105,  103,  106,  102,  104,  107,  103,  105,
      106,  106,  103,   77,  107,  105,  108,  106,  117,   66,
      107,  117,  107,  108,  108,  109,  106,  117,  117,  108,

       60,  259,  109,  109,   56,  110,  126,  110,  109,  110,
      111,  109,  111,  126,  111,  127,  122,  122,  110,  126,
      259,  260,  127,  111,   55,   52,  128,  122,  127,  129,
      128,  117,  122,  128,  130,  141,  129,  141,   31,  128,
      260,  130,  129,   26,  129,  131,  141,  130,  132,  132,
      130,  130,  131,  133,   23,  132,  134,  133,  131,   15,
      133,  132,   10,  134,  135,  136,  133,  134,  135,  134,
      139,  135,  136,  137,  138,    8,  257,  135,  136,  139,
      137,  138,  138,  140,  159,  159,  137,  138,    7,  140,
      140,  257,  257,    3,    0,  159,  140,  139,  142,    0,

      142,  143,  142,  143,  139,  144,  146,  144,  146,  143,
      139,  142,  143,  145,  147,  145,  144,  146,  145,  148,
      147,  148,  147,  149,  145,  149,  148,  149,  151,  197,
      148,  147,  150,  149,  150,  151,  149,  152,  197,  150,
      155,  151,  155,  150,  152,  152,  153,  154,  165,  153,
      152,  155,    0,  153,  154,  160,  160,  165,    0,  153,
      154,  162,  184,  162,  163,  163,  160,  163,  164,  184,
      164,  166,  162,  166,    0,  184,  163,    0,  166,  164,
        0,  168,  166,  168,  167,  165,  167,  165,  167,  168,
        0,  169,  168,  169,    0,    0,  165,  167,  170,  171,

      170,  171,  169,  172,  173,  172,  173,    0,  172,  170,
      171,  173,    0,  185,  172,  173,  174,  177,  174,  177,
      185,  185,  178,  186,  178,  186,  185,  174,  177,  178,
      179,    0,  179,  178,  186,  180,  179,  180,  181,  227,
      180,  179,  182,  181,  182,  181,  180,  187,  227,  182,
      183,  188,    0,  182,  181,  187,  183,  187,  183,  188,
      189,  188,  189,    0,    0,    0,  187,  183,  190,    0,
      188,  189,  190,  191,  190,  191,    0,  204,  192,    0,
      192,    0,  193,  190,  191,  192,  204,    0,  193,  192,
      193,  196,  199,  196,  199,  200,  201,  200,  201,  193,

        0,    0,  196,  199,  202,    0,  200,  201,    0,  203,
      202,  203,  202,    0,  204,    0,  204,  208,  205,  208,
      203,  202,  206,    0,  205,  204,  205,  206,  208,  206,
      207,  209,  207,  209,  210,  205,  210,  207,  206,  211,
        0,  207,  209,  245,  212,  210,  211,    0,  211,  212,
      214,  212,  245,  213,  214,    0,  214,  211,    0,    0,
      212,  213,  215,  213,  215,  214,    0,  216,  217,  215,
        0,    0,  213,  215,  216,  217,  218,  220,  218,  220,
      216,  217,  219,  223,  219,  223,  219,  218,  220,  225,
      224,  223,  224,    0,  223,  219,    0,  224,  225,    0,

      226,  224,  226,  229,  230,  229,  230,    0,    0,    0,
      231,  226,    0,    0,  229,  230,  231,    0,  231,  232,
      233,  232,  233,  234,    0,  234,  225,  231,  225,    0,
      232,  233,    0,  235,  234,  235,  236,  225,  236,  237,
      238,  237,  238,    0,  235,    0,  239,  236,    0,    0,
      237,  238,  239,  240,  239,  240,    0,    0,  244,  243,
      244,    0,    0,  239,  240,  243,  247,  243,  247,  244,
        0,  247,  248,  251,  249,  251,  243,  247,    0,  248,
      249,  248,  249,  253,  254,  253,  254,    0,  251,  251,
      248,  249,    0,    0,  253,  254,  255,  256,  255,  256,

      258,  258,    0,  258,    0,  258,    0,  255,  256,  261,
      261,    0,  261,    0,  261,    0,    0,  258,  258,  258,
        0,    0,    0,    0,    0,  261,  261,  264,  264,    0,
      264,    0,  264,  261,    0,  265,  265,    0,  265,    0,
      265,    0,  266,  266,  264,  266,    0,  266,    0,    0,
        0,  264,  265,    0,  258,    0,    0,    0,  266,  266,
        0,    0,    0,  261,    0,    0,  266,  267,  267,    0,
      267,    0,  267,    0,    0,    0,    0,    0,    0,    0,
        0,  264,    0,    0,  267,    0,    0,    0,    0,  265,
        0,  267,    0,    0,    0,    0,  266,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  267,  269,  269,    0,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,    0,    0,    0,
      271,  272,    0,    0,    0,  272,  272,  272,  272,  273,
        0,    0,    0,  273,    0,  273,  274,    0,    0,  274,
      274,  274,    0,  274,  275,  275,  275,  275,  275,    0,
      275,    0,  275,  275,    0,    0,    0,  275,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  277,  277,    0,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  279,    0,  279,    0,    0,    0,    0,
        0,  279,  280,    0,    0,    0,    0,    0,  280,    0,
      280,  281,  281,  281,    0,  281,  281,    0,    0,    0,
        0,  281,    0,    0,  281,  282,  282,  282,    0,  282,
        0,    0,    0,    0,    0,  282,    0,    0,  282,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
	#include <stdio.h>
	#include <string.h>
	#include <stdlib.h>
	#include "y.tab.h"

	struct symboltable
	{
		char name[100];
		char class[100];
		char type[100];
		char value[100];
		char dimension[100];
		int nesting_val;
		int lineno;
		int length;
		int params_count;
	}ST[1007];

	struct constanttable
	{
		char name[100];
		char type[100];
		int length;
	}CT[1007];

	int current_nesting = 0;
	int params_count = 0;
	char line_dec_type = 'n';
	extern int yylval;

	void set_line_dec_type(char type){
		line_dec_type = type;
	}
	int check_line_dec_type(char type_to_check){
		return (line_dec_type == type_to_check);
	}

	char array_dim_str[10000] = "";

	void append_dim(int* val_to_append){
		char temp[1000];
		sprintf(temp," %d",val_to_append);
		strcat(array_dim_str,temp);
	}

	int hash(char *str)
	{
		int value = 0;
		for(int i = 0 ; i < strlen(str) ; i++)
		{
			value = 10*value + (str[i] - 'A');
			value = value % 1007;
			while(value < 0)
				value = value + 1007;
		}
		return value;
	}

	int lookupST(char *str)
	{
		int value = hash(str);
		if(ST[value].length == 0)
		{
			return 0;
		}
		else if(strcmp(ST[value].name,str)==0)
		{
			
			return value;
		}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1007)
			{
				if(strcmp(ST[i].name,str)==0)
				{
					
					return i;
				}
			}
			return 0;
		}
	}

	int lookupCT(char *str)
	{
		int value = hash(str);
		if(CT[value].length == 0)
			return 0;
		else if(strcmp(CT[value].name,str)==0)
			return 1;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1007)
			{
				if(strcmp(CT[i].name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}

	void insertSTline(char *str1, int line)
	{
		for(int i = 0 ; i < 1007 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0)
			{
				ST[i].lineno = line;
			}
		}
	}


	void insertST(char *str1, char *str2)
	{
		if(lookupST(str1))
		{
			if(strcmp(ST[lookupST(str1)].class,"Identifier")==0 && strcmp(str2,"Array Identifier")==0)
			{
				printf("Error use of array\n");
				exit(0);
			}	
			return;
		}
		else
		{
			int value = hash(str1);
			if(ST[value].length == 0)
			{
				strcpy(ST[value].name,str1);
				strcpy(ST[value].class,str2);
				ST[value].length = strlen(str1);
				ST[value].nesting_val = current_nesting;
				ST[value].params_count = -1;
				insertSTline(str1,yylineno);
				return;
			}

			int pos = 0;

			for (int i = value + 1 ; i!=value ; i = (i+1)%1007)
			{
				if(ST[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(ST[pos].name,str1);
			strcpy(ST[pos].class,str2);
			ST[pos].length = strlen(str1);
			ST[pos].nesting_val = current_nesting;
			ST[pos].params_count = -1;
		}
	}

	void insertSTtype(char *str1, char *str2)
	{
		for(int i = 0 ; i < 1007 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0)
			{
				strcpy(ST[i].type,str2);
			}
		}
    }

	void insertSTvalue(char *str1, char *str2)
	{
		for(int i = 0 ; i < 1007 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0)// && ST[i].nesting_val == current_nesting)
			{
				strcpy(ST[i].value,str2);
			}
		}
		printf("\n");
	}


	void insertSTnest(char *s, int nest)
	{
		if(lookupST(s) && ST[lookupST(s)].nesting_val != 9999)
		{
             int pos = 0;
             int value = hash(s);
			for (int i = value + 1 ; i!=value ; i = (i+1)%1007)
			{
				if(ST[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(ST[pos].name,s);
			strcpy(ST[pos].class,"Identifier");
			ST[pos].length = strlen(s);
			ST[pos].nesting_val = nest;
			ST[pos].params_count = -1;
			ST[pos].lineno = yylineno;
		}
		else
		{
			for(int i = 0 ; i < 1007 ; i++)
			{
				if(strcmp(ST[i].name,s)==0 )
				{
					ST[i].nesting_val = nest;
				}
			}
		}
	}

	void insertSTparamscount(char *s, int count)
	{
		for(int i = 0 ; i < 1007 ; i++)
		{
			if(strcmp(ST[i].name,s)==0 )
			{
				ST[i].params_count = count;
			}
		}
	}

	int getSTparamscount(char *s)
	{
		for(int i = 0 ; i < 1007 ; i++)
		{
			if(strcmp(ST[i].name,s)==0 )
			{
				return ST[i].params_count;
			}
		}
		return -2;
	}

	void insertSTF(char *s)
	{
		for(int i = 0 ; i < 1007 ; i++)
		{
			if(strcmp(ST[i].name,s)==0 )
			{
				strcpy(ST[i].class,"Function");
				return;
			}
		}

	}

	void insertCT(char *str1, char *str2)
	{
		if(lookupCT(str1))
			return;
		else
		{
			int value = hash(str1);
			if(CT[value].length == 0)
			{
				strcpy(CT[value].name,str1);
				strcpy(CT[value].type,str2);
				CT[value].length = strlen(str1);
				return;
			}

			int pos = 0;

			for (int i = value + 1 ; i!=value ; i = (i+1)%1007)
			{
				if(CT[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(CT[pos].name,str1);
			strcpy(CT[pos].type,str2);
			CT[pos].length = strlen(str1);
		}
	}

	void deletedata (int nesting)
	{
		for(int i = 0 ; i < 1007 ; i++)
		{
			if(ST[i].nesting_val == nesting)
			{
				ST[i].length = 0 ;
			}
		}


	}

	int checkscope(char *s)
	{
		int flag = 0;
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].name,s)==0)
			{
				if(ST[i].nesting_val > current_nesting)
				{
					flag = 1;
				}
				else
				{
					flag = 0;
					break;
				}
			}
		}
		if(!flag)
		{
			return 1;
		}
		else
		{
			return 0;
		}
	}

	int check_id_is_func(char *s)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].name,s)==0)
			{
				if(strcmp(ST[i].class,"Function")==0)
					return 1;
			}
		}
		return 0;
	}

	int checkarray(char *s)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].name,s)==0)
			{
				if(strcmp(ST[i].class,"Array Identifier")==0)
				{
					return 0;
				}
			}
		}
		return 1;
	}

	int duplicate(char *s)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].name,s)==0)
			{				
				if(ST[i].nesting_val == current_nesting)
				{
			        return 1;
				}
			}
		}
		
		return 0;
	}

	int check_duplicate(char* str)
	{
		for(int i=0; i<1007; i++)
		{
			if(strcmp(ST[i].name, str) == 0 && strcmp(ST[i].class, "Function") == 0)
			{
				printf("Function redeclaration not allowed\n");
				exit(0);
			}
		}
	}

	int check_declaration(char* str, char *check_type)
	{
		for(int i=0; i<1007; i++)
		{
			if(strcmp(ST[i].name, str) == 0 && strcmp(ST[i].class, "Function") == 0 || strcmp(ST[i].name,"printf")==0 )
			{
				return 1;
			}
		}
		return 0;
	}

	int check_params(char* type_specifier)
	{
		if(!strcmp(type_specifier, "void"))
		{
			printf("Parameters cannot be of type void\n");
			exit(0);
		}
		return 0;
	}

	char gettype(char *s, int flag)
	{
			for(int i = 0 ; i < 1007 ; i++ )
			{
				if(strcmp(ST[i].name,s)==0)
				{
					return ST[i].type[0];
				}
			}
		
	}

	

	void process_array_dimensions(){
		// char* cur_array_str = strtok(array_dim_str,"\n");
		// while (cur_array_str != NULL){ // <array name> dim1 dim2
		// 	char array_name[1000] = "";
		// 	char value[100];
		// 	int index = 0;

		// 	while(index < strlen(cur_array_str)){
		// 		if(cur_array_str[index] == ' ') break;
		// 		strcat(array_name, cur_array_str[index]);
		// 		index++;
		// 	}

		// 	while(index < strlen(cur_array_str)){
		// 		strcat(value, cur_array_str[index]);
		// 		index++;
		// 	}
			
		// 	printf("Array name is %s\n",array_name);
			
		// 	insertSTvalue(array_name, value);

		// 	cur_array_str = strtok(NULL,"\n");
		// }

		// char input[] = "id 1 2 3 \n id 4 5 6 \n id 7 8 9 \n";

		char *input = array_dim_str;
		char id[100];  
		char numbers[100];
		int offset = 0;
		
		while (sscanf(input + offset, "%s %[^\n]s", id, numbers) == 2) {
			offset += snprintf(NULL, 0, "%s %s", id, numbers) + 1;
			for(int i = 0 ; i < 1007 ; i++)
			{
				if(strcmp(ST[i].name,id)==0)// && ST[i].nesting_val == current_nesting)
				{
					strcpy(ST[i].value,numbers);
				}
			}
		}
		
	}

	void printST()
	{
		process_array_dimensions();


		printf("%10s | %15s | %10s | %10s | %10s | %15s | %10s |\n","symbol name", "Class", "Type","Value", "Line No.", "Nesting Count", "Count of Params");
		for(int i=0;i<100;i++) {
			printf("_");
		}
		printf("\n");
		for(int i = 0 ; i < 1007 ; i++)
		{
			if(ST[i].length == 0)
			{
				continue;
			}

			// int first_occurrance = 0;
			// int dup[1007];
			// for (int i = 0;i < 1007;i++){
			// 	dup[i] = -1;
			// }


			// for (int j = 0;j < 1007;j++){

			// 	if(strcmp(ST[i].name,ST[j].name)==0) {				
			// 		// if(ST[i].nesting_val == ST[j].nesting_val) //Remove if this thing doesn't work
			// 		{
			// 			first_occurrance = 1;
			// 			int idx = 0;
			// 			for (;idx<1007;idx++){
			// 				if (dup[idx] == -1){
			// 					dup[idx] = ST[j].lineno;
			// 					break;
			// 				}
			// 				// printf("hello");
			// 			}
			// 		}
			// 	}
			// }
			// char line_no_str[3000] = "";
			// if (!first_occurrance){
			// 	continue;
			// } else {
				
			// 	for (int idx = 0;idx < 1007;idx++){
			// 		if (dup[idx] == -1){
			// 			break;
			// 		}
			// 		printf("hi");
			// 		sprintf(line_no_str,"%s%d->",line_no_str,dup[idx]);
			// 	}
			// }

			// printf("%10s | %15s | %10s | %10s | %10s | %15d | %10d |\n",ST[i].name, ST[i].class, ST[i].type, ST[i].value, line_no_str, ST[i].nesting_val, ST[i].params_count);
			if(ST[i].params_count == -1){
				printf("%10s | %15s | %10s | %10s | %10d | %15d | %10d |\n",ST[i].name, ST[i].class, ST[i].type, ST[i].value, ST[i].lineno, ST[i].nesting_val, 0);
			} else {
				printf("%10s | %15s | %10s | %10s | %10d | %15d | %10d |\n",ST[i].name, ST[i].class, ST[i].type, ST[i].value, ST[i].lineno, ST[i].nesting_val, ST[i].params_count);
			}

			/*printf("%10s | %15s | %10s | %10s | ",ST[i].name, ST[i].class, ST[i].type, ST[i].value);
            for (int j = 0;j < 100;j++){
                if (ST[i].lineno[j] == -1) break;
                printf("%d -> ",ST[i].lineno[j]);
            }
            printf("\n");*/
		}
							// printf("hello");
    }


	void printCT()
	{
		printf("%10s | %15s\n","constant name", "constant type");
		for(int i=0;i<85;i++) {
			printf("_");
		}
		printf("\n");
		for(int i = 0 ; i < 1007 ; i++)
		{
			if(CT[i].length == 0)
				continue;

			printf("%10s | %15s\n",CT[i].name, CT[i].type);
		}

		// printf("%s\n",array_dim_str);
	}
	char curid[20];
	char curtype[20];
	char curval[20];

#line 1341 "lex.yy.c"
#line 1342 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 565 "scanner.l"

#line 1561 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 269 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1080 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 566 "scanner.l"
{yylineno++;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 567 "scanner.l"
{ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 568 "scanner.l"
{ } 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 569 "scanner.l"
{ }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 570 "scanner.l"
{ }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 571 "scanner.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 572 "scanner.l"
{ return(';'); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 573 "scanner.l"
{ return(','); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 574 "scanner.l"
{ return('{'); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 575 "scanner.l"
{ return('}'); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 576 "scanner.l"
{ return('('); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 577 "scanner.l"
{ return(')'); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 578 "scanner.l"
{ return('['); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 579 "scanner.l"
{ return(']'); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 580 "scanner.l"
{ return(':'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 581 "scanner.l"
{ return('.'); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 582 "scanner.l"
{ return SPREAD;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 585 "scanner.l"
{insertST(yytext,"Keyword");return STRING;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 586 "scanner.l"
{ insertST(yytext, "Keyword");  return CONST;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 587 "scanner.l"
{ insertST(yytext, "Keyword");  return DEFAULT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 588 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return CHAR;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 589 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return DOUBLE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 590 "scanner.l"
{ insertST(yytext, "Keyword"); return ELSE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 591 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return FLOAT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 592 "scanner.l"
{ insertST(yytext, "Keyword"); return WHILE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 593 "scanner.l"
{ insertST(yytext, "Keyword"); return DO;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 594 "scanner.l"
{ insertST(yytext, "Keyword"); return FOR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 595 "scanner.l"
{ insertST(yytext, "Keyword"); return IF;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 596 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return INT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 597 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return LONG;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 598 "scanner.l"
{ insertST(yytext, "Keyword"); return RETURN;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 599 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return SHORT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 600 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return SIGNED;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 601 "scanner.l"
{ insertST(yytext, "Keyword"); return SIZEOF;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 602 "scanner.l"
{ strcpy(curtype,yytext);   insertST(yytext, "Keyword");  return STRUCT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 603 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return ENUM;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 604 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return UNION;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 605 "scanner.l"
{ insertST(yytext, "Keyword");   return UNSIGNED;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 606 "scanner.l"
{ strcpy(curtype,yytext);   insertST(yytext, "Keyword");  return VOID;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 607 "scanner.l"
{ insertST(yytext, "Keyword");  return BREAK;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 608 "scanner.l"
{ insertST(yytext, "Keyword");  return SWITCH;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 609 "scanner.l"
{ insertST(yytext, "Keyword");  return CASE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 610 "scanner.l"
{ insertST(yytext, "Keyword");  return CONTINUE;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 612 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return INTs;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 613 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return FLOATs;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 614 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return CHARs;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 615 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return DOUBLEs;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 617 "scanner.l"
{ insertST(yytext, "Keyword"); return AUTO; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 618 "scanner.l"
{ insertST(yytext, "Keyword"); return STATIC; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 619 "scanner.l"
{ insertST(yytext, "Keyword"); return REGISTER; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 620 "scanner.l"
{ insertST(yytext, "Keyword"); return EXTERN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 621 "scanner.l"
{ insertST(yytext, "Keyword"); return EXTERN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 622 "scanner.l"
{ insertST(yytext, "Keyword"); return INLINE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 624 "scanner.l"
{ insertST(yytext, "Keyword");  return PRINTF;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 625 "scanner.l"
{ insertST(yytext, "Keyword");  return SCANF;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 628 "scanner.l"
{ return increment_operator; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 629 "scanner.l"
{ return decrement_operator; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 630 "scanner.l"
{ return leftshift_operator; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 631 "scanner.l"
{ return rightshift_operator; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 632 "scanner.l"
{ return lessthan_assignment_operator; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 633 "scanner.l"
{ return lessthan_operator; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 634 "scanner.l"
{ return greaterthan_assignment_operator; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 635 "scanner.l"
{ return greaterthan_operator; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 636 "scanner.l"
{ return equality_operator; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 637 "scanner.l"
{ return inequality_operator; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 638 "scanner.l"
{ return AND_operator; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 639 "scanner.l"
{ return OR_operator; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 640 "scanner.l"
{ return caret_operator; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 641 "scanner.l"
{ return multiplication_assignment_operator; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 642 "scanner.l"
{ return division_assignment_operator; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 643 "scanner.l"
{ return modulo_assignment_operator; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 644 "scanner.l"
{ return addition_assignment_operator; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 645 "scanner.l"
{ return subtraction_assignment_operator; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 646 "scanner.l"
{ return leftshift_assignment_operator; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 647 "scanner.l"
{ return rightshift_assignment_operator; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 648 "scanner.l"
{ return AND_assignment_operator; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 649 "scanner.l"
{ return XOR_assignment_operator; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 650 "scanner.l"
{ return OR_assignment_operator; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 651 "scanner.l"
{ return amp_operator; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 652 "scanner.l"
{ return exclamation_operator; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 653 "scanner.l"
{ return tilde_operator; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 654 "scanner.l"
{ return subtract_operator; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 655 "scanner.l"
{ return add_operator; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 656 "scanner.l"
{ return multiplication_operator; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 657 "scanner.l"
{ return division_operator; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 658 "scanner.l"
{ return modulo_operator; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 659 "scanner.l"
{ return pipe_operator; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 660 "scanner.l"
{ return assignment_operator;}
	YY_BREAK
case 89:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 662 "scanner.l"
{strcpy(curval,yytext); insertCT(yytext,"String Constant"); return string_constant;}
	YY_BREAK
case 90:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 663 "scanner.l"
{strcpy(curval,yytext); insertCT(yytext,"Character Constant"); return character_constant;}
	YY_BREAK
case 91:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 664 "scanner.l"
{strcpy(curid,yytext); insertST(yytext, "Array Identifier"); strcat(array_dim_str,"\n");strcat(array_dim_str,yytext); return array_identifier;}
	YY_BREAK
case 92:
/* rule 92 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 665 "scanner.l"
{strcpy(curval,yytext); insertCT(yytext, "Number Constant"); yylval = atoi(yytext); return integer_constant;}
	YY_BREAK
case 93:
/* rule 93 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 666 "scanner.l"
{strcpy(curval,yytext); insertCT(yytext, "Floating Constant"); return float_constant;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 667 "scanner.l"
{strcpy(curid,yytext); insertST(curid,"Identifier"); return identifier;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 669 "scanner.l"
{
		if(yytext[0]=='#')
		{
			printf("Error in Pre-Processor directive at line no. %d\n",yylineno);
		}
		else if(yytext[0]=='/')
		{
			printf("ERR_UNMATCHED_COMMENT at line no. %d\n",yylineno);
		}
		else if(yytext[0]=='"')
		{
			printf("ERR_INCOMPLETE_STRING at line no. %d\n",yylineno);
		}
		else
		{
			printf("ERROR at line no. %d\n",yylineno);
		}
		printf("%s\n", yytext);
		return 0;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 690 "scanner.l"
ECHO;
	YY_BREAK
#line 2149 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 269 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 269 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 268);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 690 "scanner.l"

